var tbl = document.getElementById('ticketDetailsView'); 
var account = tbl.getElementsByTagName('td')[7]; 
var locationNum = account.innerHTML.slice(-6);
var customerNum = account.innerHTML.slice(0,6);
var formNode = document.getElementsByName('form1')[0];
formNode.insertAdjacentHTML('afterend', '<div id="iGlass"><button type="button" onclick="window.open(`https://noc.iglass.net/jglass/cpe/accountView.htm?account=' + locationNum + '`, `_blank`)">Open in iGlass</button></div>');
var iGlassNode = document.getElementById('iGlass');
iGlassNode.insertAdjacentHTML('afterend', '<div id="Summary"><button type="button" onclick="window.open(`http://eusvr41/CustomerSummary/default.aspx?CustNbr=' + customerNum + '&LocationID=' + locationNum + '`, `_blank`)">Customer Summary</button></div>');
var summaryNode = document.getElementById('Summary');
summaryNode.insertAdjacentHTML('afterend', '<div id="RPX"><button type="button" onclick="window.open(`https://www.rpx-momentum.com/RPX/Account/SearchCustomer.aspx?quicksearch=' + locationNum + '`, `_blank`)">RPX Account</button></div>');